---
apiVersion: v1  # Utilise l'API de version v1 pour les services.
kind: Service  # Déclare une ressource de type Service.
metadata:
  name: myevent-service  # Nom unique du service dans le namespace.
  namespace: myevent-dev  # Namespace auquel appartient ce service.
spec:
  type: NodePort  # Définit que le service est accessible depuis l'extérieur du cluster via un port du nœud.
  selector:
    app: myevent  # Lie ce service aux pods qui ont le label `app: myevent`.
  ports:
  - protocol: TCP  # Protocole utilisé pour la communication.
    port: 80  # Port exposé par le service dans le cluster.
    targetPort: 80  # Port sur lequel l'application dans le pod écoute.
    nodePort: 30001  # Port du nœud sur lequel le service sera accessible.
---
apiVersion: v1
kind: Service
metadata:
  name: myevent-service
  namespace: myevent-prod
spec:
  type: NodePort
  selector:
    app: myevent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: myevent-service
  namespace: myevent-qualif
spec:
  type: NodePort
  selector:
    app: myevent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003